### ISSUE TITLE
Błąd instalacji modułu

### ISSUE THREAD

**Issue by Lioheart** [oswida/foundry-vtt-cairn-pl#1]
Hej,

Nie można zainstalować modułu. Chciałem wypróbować system i tłumaczenie, ale plik module.json jest źle skonstruowany. Brakuje linii:

  "manifest": "https://gitlab.com/xxx/module.json",
  "download": "https://gitlab.com/xxx/foundry-vtt-cairn-pl.zip ",
  
Jeśli potrzebna pomoc, mogę utworzyć poprawny plik module.json

**Comment by oswida** [comment]
Cześć,
Sprawdź proszę teraz.

**Comment by Lioheart** [comment]
O, super. Teraz działa i mogłem już sprawdzić. Dzięki.
Szkoda, że jeszcze wszystko nie jest przetłumaczone (np. potwory).

**Comment by oswida** [comment]
Moje możliwości czasowe są ograniczone, rozwijam jednocześnie główny system do Cairn oraz wraz z Yochaiem Kettlewright (dedykowaną aplikację do Cairn).
